# Generated by Django 5.1.2 on 2024-10-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Адрес')),
                ('type', models.CharField(choices=[('INS', 'Подключение'), ('BRD', 'Аварийный выезд'), ('UPG', 'Модернизация'), ('DEC', 'Демонтаж')], default='BRD', max_length=3)),
                ('description', models.TextField(verbose_name='Описание')),
                ('closed', models.CharField(choices=[('OP', 'Открыта'), ('CL', 'Закрыта')], default='OP', max_length=2)),
            ],
            options={
                'verbose_name': 'Tasks for the installers',
                'verbose_name_plural': 'Tasks for the installers',
            },
        ),
    ]
