# Generated by Django 5.1.2 on 2024-10-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='closed',
            field=models.BooleanField(default=1),
        ),
    ]
